# Generated by Django 3.2.13 on 2022-05-21 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_default_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, error_messages={'invalid': 'Invalid phone number'}, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{11,15}$')]),
        ),
    ]
