# Generated by Django 3.2.13 on 2022-05-25 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=254, validators=[django.core.validators.RegexValidator(code='invalid', message='Only alphabetical values accepted', regex='^[a-zA-Z ]+[a-zA-Z]+$')]),
        ),
    ]
