# Generated by Django 3.2.13 on 2022-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=254)),
                ('blog_content', models.TextField()),
                ('author', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
