# Generated by Django 3.2.13 on 2022-05-20 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogcomment_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_content',
            new_name='blog_content_one',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_created',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_content_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_content_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
