# Generated by Django 3.2.13 on 2022-05-21 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'invalid': 'Invalid phone number'}, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{11,15}$')]),
        ),
    ]
