# Generated by Django 3.2.13 on 2022-05-21 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=1, error_messages={'invalid': 'Invalid phone number'}, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{11,15}$')]),
            preserve_default=False,
        ),
    ]
