# Generated by Django 3.2.13 on 2022-05-21 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
