# Generated by Django 3.2.13 on 2022-05-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220429_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kids_shoe_sizes',
            new_name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kids_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ladies_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='men_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_sizes',
        ),
    ]
